version: '3.3'

services:
  db:
    build: .
    command: postgres -c config_file=/etc/postgresql.conf
    volumes:
      - .:/tmp/pg_rollup
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
