name: tests
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  #schedule:
    #- cron:  '0 12 10 * *' # Monthly at noon on the tenth
jobs:
  docker:
    strategy:
      matrix:
        POSTGRES_VERSION: [10, 11, 12, 13]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker
      run: |
        docker-compose build --build-arg BASE_IMAGE_VERSION=$POSTGRES_VERSION
        docker-compose up -d
        sleep 20
        docker-compose exec -T db make installcheck
        docker-compose down
